version: '3.8'

services:
  film_suggestion:
    build: .
    environment:
      CHROME_DRIVER_PATH: ${CHROME_DRIVER_PATH}
    volumes:
      - .:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
